name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Deploys when pushing to the main branch; adjust if using a different branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set iup Node.js
      uses: actions/setup-node@v3
    
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Run Unit Tests
      working-directory: ./backend
      run: npm test

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker europe-north1-docker.pkg.dev

    - name: Build and push frontend Docker image
      run: |
        docker build -t europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/eu-north1-docker-repo/react-frontend ./frontend
        docker push europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/eu-north1-docker-repo/react-frontend

    - name: Deploy frontend to Cloud Run
      run: |
        gcloud run deploy react-frontend \
          --image europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/eu-north1-docker-repo/react-frontend \
          --region europe-north1 \
          --platform managed \
          --allow-unauthenticated

    - name: Build and push backend Docker image
      run: |
        docker build -t europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/eu-north1-docker-repo/node-backend ./backend
        docker push europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/eu-north1-docker-repo/node-backend

    - name: Deploy backend to Cloud Run
      run: |
        gcloud run deploy node-backend \
          --image europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/eu-north1-docker-repo/node-backend \
          --region europe-north1 \
          --platform managed \
          --service-account=cloud-run-service-account@idata2502-cloudproject.iam.gserviceaccount.com \
          --allow-unauthenticated \
